'use client';

import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, BorderStyle, HeadingLevel, PageBreak,
  PageNumber, VerticalAlign, convertInchesToTwip
} from 'docx';
import { saveAs } from 'file-saver';

/**
 * Build and download a DOCX document from all section data.
 */
export async function exportToDocx(header, sections) {
  const children = [];

  // ── Cover / Header ──
  children.push(
    new Paragraph({
      children: [new TextRun({ text: header.namaSekolah || 'Nama Sekolah', bold: true, size: 28, color: '1B4F72' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: 'LAMPIRAN MODUL AJAR', bold: true, size: 24, color: '1B4F72' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: header.judulModul || '', size: 22 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
  );

  // Meta bar
  const metaPairs = [
    ['Mata Pelajaran', header.mataPelajaran],
    ['Kode Modul', header.kodeModul],
    ['No. TP', header.nomorTP],
    ['Fase/Kelas', header.faseKelas],
    ['Semester', header.semester],
    ['Tahun', header.tahunPelajaran],
    ['Guru', header.namaGuru],
  ];

  const metaTableRows = [];
  // Row 1
  const row1Cells = metaPairs.slice(0, 4).map(([label, val]) =>
    new TableCell({
      children: [new Paragraph({ children: [new TextRun({ text: label + ':', bold: true, size: 16 })], spacing: { after: 0 } }),
                 new Paragraph({ children: [new TextRun({ text: val || '-', size: 16 })], spacing: { after: 0 } })],
      verticalAlign: VerticalAlign.CENTER,
    })
  );
  if (row1Cells.length > 0) metaTableRows.push(new TableRow({ children: row1Cells }));

  const row2Cells = metaPairs.slice(4).map(([label, val]) =>
    new TableCell({
      children: [new Paragraph({ children: [new TextRun({ text: label + ':', bold: true, size: 16 })], spacing: { after: 0 } }),
                 new Paragraph({ children: [new TextRun({ text: val || '-', size: 16 })], spacing: { after: 0 } })],
      verticalAlign: VerticalAlign.CENTER,
    })
  );
  if (row2Cells.length > 0) metaTableRows.push(new TableRow({ children: row2Cells }));

  children.push(
    new Table({
      rows: metaTableRows,
      width: { size: 100, type: WidthType.PERCENTAGE },
    }),
    new Paragraph({ spacing: { after: 200 }, children: [] }),
  );

  // ── Sections ──
  const enabledKeys = Object.keys(sections).filter(k => sections[k]?.enabled);

  for (let si = 0; si < enabledKeys.length; si++) {
    const key = enabledKeys[si];
    const sec = sections[key];
    const d = sec?.data;

    // Page break between sections
    if (si > 0) {
      children.push(new Paragraph({ children: [new PageBreak()] }));
    }

    const label = SECTION_LABELS[key] || key;
    children.push(
      new Paragraph({
        children: [new TextRun({ text: label, bold: true, size: 22, color: '1B4F72' })],
        spacing: { before: 200, after: 200 },
        alignment: AlignmentType.CENTER,
      })
    );

    // Render section content
    switch (key) {
      case 'lkpd': renderLKPD(children, header, d); break;
      case 'formatif': renderFormatif(children, header, d); break;
      case 'sumatif': renderSumatif(children, header, d); break;
      case 'rubrik': renderRubrik(children, header, d); break;
      case 'materi': renderMateri(children, header, d); break;
      case 'media': renderMedia(children, header, d); break;
      case 'refleksi': renderRefleksi(children, header, d); break;
      case 'pengayaan': renderListSection(children, 'Aktivitas Pengayaan', d?.pengayaanList); break;
      case 'remediasi': renderListSection(children, 'Aktivitas Remediasi', d?.remediasiList); break;
    }
  }

  // ── Generate DOCX (F4 / justify) ──
  const F4_WIDTH_TWIP = 12240;   // 210mm = 8.5"
  const F4_HEIGHT_TWIP = 18720;  // 330mm = 13"
  const MARGIN_TWIP = 1134;      // ~2cm

  const doc = new Document({
    title: `Lampiran Modul - ${header.judulModul || header.mataPelajaran || 'Untitled'}`,
    description: 'Generated by Lampiran Generator',
    styles: {
      default: {
        document: {
          run: { size: 22, font: 'Times New Roman' },
          paragraph: { alignment: AlignmentType.JUSTIFIED, spacing: { line: 360 } },
        },
      },
    },
    sections: [{
      properties: {
        page: {
          size: { width: F4_WIDTH_TWIP, height: F4_HEIGHT_TWIP },
          margin: { top: MARGIN_TWIP, bottom: MARGIN_TWIP, left: MARGIN_TWIP, right: MARGIN_TWIP },
        },
      },
      children,
    }],
  });

  const blob = await Packer.toBlob(doc);
  const fileName = `Lampiran_${header.kodeModul || header.mataPelajaran || 'Modul'}.docx`;
  saveAs(blob, fileName);
}

/* ── SECTION LABELS ── */
const SECTION_LABELS = {
  lkpd: 'LEMBAR KERJA PESERTA DIDIK (LKPD)',
  formatif: 'PENILAIAN FORMATIF',
  sumatif: 'PENILAIAN SUMATIF',
  rubrik: 'RUBRIK PENILAIAN',
  materi: 'BAHAN AJAR / MATERI',
  media: 'MEDIA PEMBELAJARAN',
  refleksi: 'REFLEKSI PEMBELAJARAN',
  pengayaan: 'AKTIVITAS PENGAYAAN',
  remediasi: 'AKTIVITAS REMEDIASI',
};

/* ── Helpers ── */
function t(text, opts = {}) {
  return new TextRun({ text: String(text || '-'), size: opts.size || 20, ...opts });
}
function p(children, opts = {}) {
  return new Paragraph({ children: Array.isArray(children) ? children : [t(children)], spacing: { after: opts.after || 80 }, ...opts });
}
function pBold(text) {
  return p([t(text, { bold: true, size: 18 })]);
}

function heading(children, text) {
  children.push(p([t(text, { bold: true, size: 18 })]));
}

function cell(paragraphs, opts = {}) {
  return new TableCell({ children: Array.isArray(paragraphs) ? paragraphs : [paragraphs], ...opts });
}

function makeTable(headers, rows) {
  const headerRow = new TableRow({
    children: headers.map(h => cell(p([t(h, { bold: true, size: 16 })]), { shading: { fill: 'EAF2F8' } })),
    tableHeader: true,
  });
  const dataRows = rows.map(rowData =>
    new TableRow({ children: rowData.map(cellText => cell(p(t(String(cellText || '-'), { size: 16 })))) })
  );
  return new Table({ rows: [headerRow, ...dataRows], width: { size: 100, type: WidthType.PERCENTAGE } });
}

/* ── LKPD ── */
function renderLKPD(children, header, d) {
  if (!d) return;
  heading(children, 'Identitas LKPD');
  children.push(makeTable(
    ['Field', 'Value'],
    [
      ['Mata Pelajaran', header.mataPelajaran],
      ['Fase/Kelas', header.faseKelas],
      ['Judul Kegiatan', d.judulKegiatan],
      ['Alokasi Waktu', d.alokasiWaktu],
      ['Tujuan', d.tujuan],
    ].map(row => [row[0], row[1]])
  ));
  const kegiatan = d.kegiatan || [];
  if (kegiatan.length > 0) {
    heading(children, 'Langkah Kegiatan');
    children.push(makeTable(
      ['#', 'Tanggal', 'Deskripsi', 'Stimulus'],
      kegiatan.map((k, i) => [i + 1, k.tanggal, k.deskripsi, k.stimulus])
    ));
  }
}

/* ── Formatif ── */
function renderFormatif(children, header, d) {
  if (!d) return;
  children.push(makeTable(
    ['Field', 'Value'],
    [
      ['Teknik Penilaian', d.teknik],
      ['Jenis Penilaian', (d.jenisPenilaian || []).join(', ')],
    ]
  ));
  const instrumen = d.instrumen || [];
  if (instrumen.length > 0) {
    heading(children, 'Instrumen Penilaian');
    children.push(makeTable(
      ['#', 'Aspek', 'Indikator', 'Skor'],
      instrumen.map((r, i) => [i + 1, r.aspek, r.indikator, r.skor])
    ));
  }
}

/* ── Sumatif ── */
function renderSumatif(children, header, d) {
  if (!d) return;
  children.push(makeTable(['Field', 'Value'], [['Bentuk Penilaian', d.bentuk]]));
  const instrumen = d.instrumen || [];
  if (instrumen.length > 0) {
    heading(children, 'Instrumen Penilaian');
    children.push(makeTable(
      ['#', 'Uraian / Soal', 'Bobot'],
      instrumen.map((r, i) => [i + 1, r.uraian, r.bobot])
    ));
  }
  if (d.kkm) children.push(p([t('KKM: ' + d.kkm, { bold: true })]));
}

/* ── Rubrik ── */
function renderRubrik(children, header, d) {
  if (!d) return;
  const kriteria = d.kriteria || [];
  if (kriteria.length > 0) {
    heading(children, 'Kriteria Penilaian');
    children.push(makeTable(
      ['#', 'Kriteria', 'Deskripsi / Skala'],
      kriteria.map((r, i) => [i + 1, r.kriteria, r.deskripsi])
    ));
  }
}

/* ── Materi ── */
function renderMateri(children, header, d) {
  if (!d) return;
  const list = d.materiList || [];
  if (list.length > 0) {
    heading(children, 'Materi Pembelajaran');
    list.forEach((m, i) => children.push(p(`${i + 1}. ${m || '-'}`, { indent: 200 })));
  }
  if (d.sumber) children.push(p([t('Sumber Referensi: ', { bold: true }), t(d.sumber)], { spacing: { before: 100 } }));
}

/* ── Media ── */
function renderMedia(children, header, d) {
  if (!d) return;
  const list = d.mediaList || [];
  if (list.length > 0) {
    heading(children, 'Daftar Media');
    children.push(makeTable(
      ['#', 'Jenis Media', 'Nama / Deskripsi'],
      list.map((r, i) => [i + 1, r.jenis, r.deskripsi])
    ));
  }
  if (d.catatan) children.push(p([t('Catatan: ', { bold: true }), t(d.catatan)]));
}

/* ── Refleksi ── */
function renderRefleksi(children, header, d) {
  if (!d) return;
  const list = d.refleksiList || [];
  if (list.length > 0) {
    heading(children, 'Pertanyaan Refleksi');
    children.push(makeTable(
      ['#', 'Pertanyaan', 'Target'],
      list.map((r, i) => [i + 1, r.pertanyaan, r.target])
    ));
  }
}

/* ── Pengayaan / Remediasi (list-based) ── */
function renderListSection(children, title, list) {
  if (!list || list.length === 0) return;
  heading(children, title);
  list.forEach((item, i) => children.push(p(`${i + 1}. ${item || '-'}`, { indent: 200 })));
}
